// Catálogo do manual base — dados para autopreenchimento da ficha.
// Gerado a partir de sistema-base/listas/*. Transcrição fiel do manual.

export type PropKey = "ARRE" | "AGAR" | "CORT" | "CONT" | "DEFL" | "PERF" | "PROJ";

export type CatArma = {
  nome: string;            // nome principal (o primeiro nome da linha da tabela)
  variantes?: string[];    // demais nomes listados na mesma linha
  tipo: string;            // tamanho: "Leve" | "Média" | "Pesada" | "" (desarmado)
  categoria: string;       // classe de alcance da coluna: "Curta" (CURT.) | "Longa" (LONG.) | ""
  custoPA: string;         // só o número, ex: "2", "4", "6", "1", "" (improvisada sem PA)
  alcance: string;         // ex: "1m", "2m a 5m", "1m / 2m a 5m", ""
  dano: string;            // ex: "2d4 CONT · 1d6 PERF (+1d4 a 2 mãos)", "1d8", "1"
  props: PropKey[];        // subconjunto (NÃO inclua VERS aqui; use o campo versatil)
  versatil?: boolean;      // true se a linha tem VERS.
  distancia?: boolean;     // true para armas à distância
  preco?: string;          // ex: "6 moedas"
};

export type CatProtecao = {
  nome: string;            // p/ armaduras use "Peça leve"/"Peça média"/"Peça pesada"; p/ escudos o nome principal da linha
  variantes?: string[];    // outros nomes na mesma linha (escudos)
  classe: "Armadura" | "Escudo";
  tipo: string;            // "Leve" | "Média" | "Pesada"
  redPA: string;           // ex: "-1"
  redDano: string;         // ex: "-1"
  durabilidade: string;    // ex: "10"
  paUso?: string;          // escudos: PA para levantar guarda, só número ex "2"
  preco?: string;
};

export type CatHabilidade = {
  nome: string;
  atributo: "Físico" | "Ágil" | "Mental" | "Social" | "Geral";
  custoPA: string;         // custo de PA de ativação conforme o manual (ex: "1", "2", "1 + PA da arma"); transcreva o texto de forma curta
  valorCompra: string;     // custo de compra em exp (só o número da coluna de custo de compra, nível base)
  efeito: string;          // 1 frase curta resumindo a Descrição
  requisitos?: string;     // requisitos de uso, curto; opcional
};

export type CatTraco = {
  nome: string;
  categoria: "Técnica" | "Maestria" | "Aspecto";
  atributo?: string;       // quando o manual indicar (técnicas têm atributo)
  valorCompra: string;     // custo de compra em exp (só o número)
  efeito: string;          // 1 frase curta
  requisitos?: string;
};

// ---------------------------------------------------------------------------
// ARMAS
// ---------------------------------------------------------------------------

export const CAT_ARMAS: CatArma[] = [
  // --- Corpo a corpo ---
  {
    nome: "Ataque desarmado",
    tipo: "",
    categoria: "",
    custoPA: "1",
    alcance: "1m",
    dano: "1",
    props: ["CONT"],
  },
  {
    nome: "Manoplas com cravos",
    variantes: ["Adaga de soco", "Tekkokagi", "Rapieira"],
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "1m",
    dano: "1d4",
    props: ["PERF"],
    preco: "6 moedas",
  },
  {
    nome: "Shuriken",
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "2m a 5m",
    dano: "1d4",
    props: ["PERF", "ARRE"],
    preco: "4 moedas",
  },
  {
    nome: "Faca",
    variantes: ["Foice de mão"],
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "1m",
    dano: "1d4",
    props: ["CORT", "PERF"],
    preco: "3 moedas",
  },
  {
    nome: "Bastão curto",
    variantes: ["Tonfa", "Martelo Curto"],
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "1m / 2m a 5m",
    dano: "1d4",
    props: ["CONT", "ARRE"],
    preco: "4 moedas",
  },
  {
    nome: "Adaga",
    variantes: ["Kukri", "Kunai"],
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "1m / 2m a 5m",
    dano: "1d4",
    props: ["CORT", "PERF", "ARRE"],
    preco: "6 moedas",
  },
  {
    nome: "Chakram",
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "1m / 2m a 5m",
    dano: "1d4",
    props: ["CORT", "ARRE"],
    preco: "20 moedas",
  },
  {
    nome: "Escudo de arremesso",
    tipo: "Leve",
    categoria: "Curta",
    custoPA: "2",
    alcance: "2m a 5m",
    dano: "1d4",
    props: ["CONT", "DEFL", "ARRE"],
    preco: "12 moedas",
  },
  {
    nome: "Facão",
    variantes: ["Machete", "Peixeira"],
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m",
    dano: "1d8",
    props: ["CORT"],
    preco: "4 moedas",
  },
  {
    nome: "Espada Curta",
    variantes: ["Foice curta", "Cimitarra", "Falcione", "Khopesh"],
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m",
    dano: "1d8 CORT · 1d6 PERF",
    props: ["CORT", "PERF"],
    preco: "8 moedas",
  },
  {
    nome: "Lança curta",
    variantes: ["Seta"],
    tipo: "Média",
    categoria: "Longa",
    custoPA: "4",
    alcance: "2m",
    dano: "1d6",
    props: ["PERF", "ARRE"],
    preco: "8 moedas",
  },
  {
    nome: "Gato de nove caudas",
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m",
    dano: "1d8",
    props: ["CORT", "AGAR"],
    preco: "32 moedas",
  },
  {
    nome: "Chicote",
    variantes: ["Corrente"],
    tipo: "Média",
    categoria: "Longa",
    custoPA: "4",
    alcance: "3m a 4m",
    dano: "1d8",
    props: ["CORT", "AGAR"],
    preco: "12 moedas",
  },
  {
    nome: "Machadinha",
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m / 2m a 4m",
    dano: "1d8",
    props: ["CORT", "ARRE"],
    preco: "6 moedas",
  },
  {
    nome: "Boomerangue",
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m / 2m a 5m",
    dano: "2d4",
    props: ["CONT", "ARRE"],
    preco: "12 moedas",
  },
  {
    nome: "Tridente",
    variantes: ["Brandistock"],
    tipo: "Média",
    categoria: "Longa",
    custoPA: "4",
    alcance: "2m a 3m",
    dano: "1d6 (+1d4 a 2 mãos)",
    props: ["PERF"],
    versatil: true,
    preco: "12 moedas",
  },
  {
    nome: "Bastão médio",
    variantes: ["Nunchaku", "Martelo Médio"],
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m",
    dano: "2d4 (+1d4 a 2 mãos)",
    props: ["CONT"],
    versatil: true,
    preco: "8 moedas",
  },
  {
    nome: "Rede",
    tipo: "Média",
    categoria: "Longa",
    custoPA: "4",
    alcance: "1m a 5m",
    dano: "0",
    props: ["AGAR", "ARRE"],
    preco: "4 moedas",
  },
  {
    nome: "Picareta de mão",
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m",
    dano: "1d6 (+1d4 a 2 mãos)",
    props: ["PERF"],
    versatil: true,
    preco: "5 moedas",
  },
  {
    nome: "Machado",
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m / 2m a 4m",
    dano: "1d8 (+1d4 a 2 mãos)",
    props: ["CORT", "ARRE"],
    versatil: true,
    preco: "8 moedas",
  },
  {
    nome: "Clava",
    variantes: ["Maça"],
    tipo: "Média",
    categoria: "Curta",
    custoPA: "4",
    alcance: "1m",
    dano: "2d4 CONT · 1d6 PERF (+1d4 a 2 mãos)",
    props: ["CONT", "PERF"],
    versatil: true,
    preco: "6 moedas",
  },
  {
    nome: "Mangual",
    variantes: ["Maça estrela", "Espada Longa", "Bastarda", "Sabre", "Katana"],
    tipo: "Média",
    categoria: "Longa",
    custoPA: "4",
    alcance: "1m a 2m",
    dano: "1d8 CORT · 1d6 PERF (+1d4 a 2 mãos)",
    props: ["CORT", "PERF"],
    versatil: true,
    preco: "20 moedas",
  },
  {
    nome: "Kusarigama",
    variantes: ["Double-chained Kama"],
    tipo: "Média",
    categoria: "Longa",
    custoPA: "4",
    alcance: "3m a 4m",
    dano: "1d8 CORT · 2d4 CONT",
    props: ["CORT", "CONT", "AGAR", "ARRE"],
    preco: "30 moedas",
  },
  {
    nome: "Bastão grande",
    variantes: ["Setsukon"],
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "1m a 2m",
    dano: "3d4",
    props: ["CONT"],
    preco: "6 moedas",
  },
  {
    nome: "Machado Pesado",
    variantes: ["Machado de Batalha"],
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "1m a 2m",
    dano: "1d12",
    props: ["CORT"],
    preco: "10 moedas",
  },
  {
    nome: "Picareta",
    tipo: "Pesada",
    categoria: "Curta",
    custoPA: "6",
    alcance: "1m",
    dano: "1d8",
    props: ["PERF"],
    preco: "6 moedas",
  },
  {
    nome: "Martelo Grande",
    variantes: ["Martelo de batalha"],
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "1m a 2m",
    dano: "3d4",
    props: ["CONT"],
    preco: "14 moedas",
  },
  {
    nome: "Alabarda",
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "2m a 3m",
    dano: "1d8",
    props: ["PERF"],
    preco: "16 moedas",
  },
  {
    nome: "Lança montada",
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "3m",
    dano: "1d8",
    props: ["PERF"],
    preco: "9 moedas",
  },
  {
    nome: "Mangual pesado",
    variantes: ["Mangual Atroz", "Maça Pesada", "Clava pesada", "Esp. de duas lâminas"],
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "2m",
    dano: "1d12 CORT · 1d8 PERF",
    props: ["CORT", "PERF"],
    preco: "14 moedas",
  },
  {
    nome: "Lança longa",
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "2m / 2m a 3m",
    dano: "1d8",
    props: ["PERF", "ARRE"],
    preco: "10 moedas",
  },
  {
    nome: "Espada Larga",
    variantes: ["montante", "Flamberge", "Foice ceifadora"],
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "2m",
    dano: "1d12 CORT · 1d8 PERF",
    props: ["CORT", "PERF"],
    preco: "12 moedas",
  },
  {
    nome: "Corrente de espinhos",
    tipo: "Pesada",
    categoria: "Longa",
    custoPA: "6",
    alcance: "3m a 4m",
    dano: "1d12",
    props: ["CORT", "AGAR"],
    preco: "16 moedas",
  },
  {
    nome: "Arma improvisada leve",
    tipo: "Leve",
    categoria: "",
    custoPA: "",
    alcance: "",
    dano: "2",
    props: ["CONT"],
  },
  {
    nome: "Arma improvisada média",
    tipo: "Média",
    categoria: "",
    custoPA: "",
    alcance: "",
    dano: "3",
    props: ["CONT"],
  },
  {
    nome: "Arma improvisada pesada",
    tipo: "Pesada",
    categoria: "",
    custoPA: "",
    alcance: "",
    dano: "4",
    props: ["CONT"],
  },

  // --- À distância (dano depende da munição) ---
  {
    nome: "Funda",
    variantes: ["Zarabatana"],
    tipo: "Leve",
    categoria: "",
    custoPA: "2",
    alcance: "4m a 7m",
    dano: "",
    props: [],
    distancia: true,
    preco: "5 moedas",
  },
  {
    nome: "Arco curto",
    variantes: ["Besta de mão"],
    tipo: "Leve",
    categoria: "",
    custoPA: "2",
    alcance: "6m a 9m",
    dano: "",
    props: [],
    distancia: true,
    preco: "20 moedas",
  },
  {
    nome: "Arco composto",
    variantes: ["Besta leve"],
    tipo: "Média",
    categoria: "",
    custoPA: "4",
    alcance: "7m a 10m",
    dano: "",
    props: [],
    distancia: true,
    preco: "30 moedas",
  },
  {
    nome: "Arco longo",
    variantes: ["Besta pesada"],
    tipo: "Pesada",
    categoria: "",
    custoPA: "6",
    alcance: "8m a 12m",
    dano: "",
    props: [],
    distancia: true,
    preco: "40 moedas",
  },
  {
    nome: "Besta de repetição",
    tipo: "Pesada",
    categoria: "",
    custoPA: "6",
    alcance: "7m a 10m",
    dano: "",
    props: [],
    distancia: true,
    preco: "80 moedas",
  },
  {
    nome: "Pistola simples",
    tipo: "Leve",
    categoria: "",
    custoPA: "2",
    alcance: "2m a 15m",
    dano: "",
    props: [],
    distancia: true,
    preco: "220 moedas",
  },
  {
    nome: "Espingarda",
    variantes: ["Arquebus", "Handgonne"],
    tipo: "Média",
    categoria: "",
    custoPA: "4",
    alcance: "1m a 5m",
    dano: "",
    props: [],
    distancia: true,
    preco: "260 moedas",
  },
  {
    nome: "Rifle",
    variantes: ["Mosquete"],
    tipo: "Pesada",
    categoria: "",
    custoPA: "6",
    alcance: "3m a 20m",
    dano: "",
    props: [],
    distancia: true,
    preco: "340 moedas",
  },
];

// ---------------------------------------------------------------------------
// PROTEÇÕES
// ---------------------------------------------------------------------------

export const CAT_PROTECOES: CatProtecao[] = [
  // Armaduras (peças genéricas por tipo)
  {
    nome: "Peça leve",
    classe: "Armadura",
    tipo: "Leve",
    redPA: "-1",
    redDano: "-1",
    durabilidade: "10",
    preco: "20 moedas",
  },
  {
    nome: "Peça média",
    classe: "Armadura",
    tipo: "Média",
    redPA: "-2",
    redDano: "-2",
    durabilidade: "25",
    preco: "60 moedas",
  },
  {
    nome: "Peça pesada",
    classe: "Armadura",
    tipo: "Pesada",
    redPA: "-3",
    redDano: "-3",
    durabilidade: "50",
    preco: "140 moedas",
  },
  // Escudos
  {
    nome: "Broquel",
    classe: "Escudo",
    tipo: "Leve",
    redPA: "-1",
    redDano: "-1",
    durabilidade: "6",
    paUso: "2",
    preco: "5 moedas",
  },
  {
    nome: "Escudo pequeno",
    classe: "Escudo",
    tipo: "Leve",
    redPA: "-1",
    redDano: "-1",
    durabilidade: "10",
    paUso: "2",
    preco: "8 moedas",
  },
  {
    nome: "Escudo médio",
    variantes: ["Cestus", "Áspide"],
    classe: "Escudo",
    tipo: "Média",
    redPA: "-2",
    redDano: "-2",
    durabilidade: "15",
    paUso: "3",
    preco: "14 moedas",
  },
  {
    nome: "Escudo Grande",
    classe: "Escudo",
    tipo: "Média",
    redPA: "-2",
    redDano: "-2",
    durabilidade: "20",
    paUso: "3",
    preco: "20 moedas",
  },
  {
    nome: "Escudo torre",
    variantes: ["Tater"],
    classe: "Escudo",
    tipo: "Pesada",
    redPA: "-3",
    redDano: "-3",
    durabilidade: "25",
    paUso: "4",
    preco: "40 moedas",
  },
];

// ---------------------------------------------------------------------------
// HABILIDADES
// ---------------------------------------------------------------------------

export const CAT_HABILIDADES: CatHabilidade[] = [
  // --- Ágil ---
  {
    nome: "Alcance corpo a corpo",
    atributo: "Ágil",
    custoPA: "3 + PA da arma (reduz por nível)",
    valorCompra: "2",
    efeito: "Aumenta o alcance ideal da arma em 1 metro; cada nível reduz o custo de PA.",
    requisitos: "Arma corpo a corpo de longo alcance (LONG); não usar armadura pesada.",
  },
  {
    nome: "Alcance à distância",
    atributo: "Ágil",
    custoPA: "2 + PA da arma",
    valorCompra: "2",
    efeito: "Aumenta a área de alcance ideal da arma à distância.",
    requisitos: "Arma à distância (DIST); não usar armadura pesada.",
  },
  {
    nome: "Arremesso improvisado",
    atributo: "Ágil",
    custoPA: "1",
    valorCompra: "2",
    efeito: "Pode arremessar armas ou objetos como se fossem armas de arremesso neste turno.",
    requisitos: "Arma/objeto leve ou média.",
  },
  {
    nome: "Arremessos concentrados",
    atributo: "Ágil",
    custoPA: "1",
    valorCompra: "2",
    efeito: "Mantém o mesmo alvo em arremessos ignorando a desvantagem de ataques múltiplos.",
    requisitos: "Arremessar arma de arremesso (ARRE).",
  },
  {
    nome: "Ataques múltiplos & leves",
    atributo: "Ágil",
    custoPA: "1",
    valorCompra: "1",
    efeito: "Muda o alvo de ataques corpo a corpo com armas leves ignorando a desvantagem de ataques múltiplos.",
    requisitos: "Armas corpo a corpo leves.",
  },
  {
    nome: "Ataques à distância concentrados",
    atributo: "Ágil",
    custoPA: "1",
    valorCompra: "2",
    efeito: "Mantém o mesmo alvo em ataques à distância ignorando a desvantagem de ataques múltiplos.",
    requisitos: "Arma à distância (DIST).",
  },
  {
    nome: "Disparada",
    atributo: "Ágil",
    custoPA: "5",
    valorCompra: "2",
    efeito: "Realiza um movimento em linha reta na direção escolhida.",
    requisitos: "Nenhuma perna desabilitada.",
  },
  {
    nome: "Golpe surpresa",
    atributo: "Ágil",
    custoPA: "1 + PA da arma",
    valorCompra: "2",
    efeito: "Realiza um golpe surpresa que causa dano adicional.",
    requisitos: "Estar escondido; armas leves corpo a corpo; não usar armadura média ou pesada.",
  },

  // --- Físico ---
  {
    nome: "Atordoar",
    atributo: "Físico",
    custoPA: "1 + PA da arma",
    valorCompra: "4",
    efeito: "Causa metade do dano da arma e atordoa o alvo, reduzindo seu PA até um descanso curto.",
    requisitos: "Escudo ou arma contundente.",
  },
  {
    nome: "Quebrar guarda",
    atributo: "Físico",
    custoPA: "1 + PA da arma",
    valorCompra: "2",
    efeito: "Força o inimigo a gastar sua guarda levantada e causa metade do dano da arma.",
    requisitos: "Arma contundente média ou pesada; alvo com guarda levantada.",
  },
  {
    nome: "Desarmar pesado",
    atributo: "Físico",
    custoPA: "1 + PA da arma",
    valorCompra: "3",
    efeito: "Ataca a arma do oponente e a derruba no chão; não causa dano.",
    requisitos: "Arma média ou pesada.",
  },
  {
    nome: "Desarmar leve",
    atributo: "Físico",
    custoPA: "1 + PA da arma",
    valorCompra: "3",
    efeito: "Ataque mirado no braço armado que derruba a arma do inimigo, causando dano normal.",
    requisitos: "Arma leve ou sem arma.",
  },
  {
    nome: "Encontrão",
    atributo: "Físico",
    custoPA: "1 + PA da arma",
    valorCompra: "2",
    efeito: "Corre 2 metros até o oponente e o empurra, causando metade do dano da arma.",
    requisitos: "Arma média ou pesada; estar a 2 metros do oponente.",
  },
  {
    nome: "Esmagar",
    atributo: "Físico",
    custoPA: "5",
    valorCompra: "2",
    efeito: "Agarra o oponente e causa dano, podendo repetir o dano nos turnos seguintes.",
    requisitos: "Não usar armas; nenhum braço desabilitado.",
  },
  {
    nome: "Investida",
    atributo: "Físico",
    custoPA: "1 + PA da arma",
    valorCompra: "3",
    efeito: "Avança até o oponente para um ataque mirado, ignorando o engajamento do alvo.",
    requisitos: "Não usar arma pesada; nenhum braço ou perna desabilitado.",
  },
  {
    nome: "Ataques múltiplos & médios",
    atributo: "Físico",
    custoPA: "1",
    valorCompra: "2",
    efeito: "Muda o alvo de ataques corpo a corpo com armas médias ignorando a desvantagem de ataques múltiplos.",
    requisitos: "Armas corpo a corpo médias.",
  },
  {
    nome: "Ataques múltiplos & pesados",
    atributo: "Físico",
    custoPA: "1",
    valorCompra: "3",
    efeito: "Muda o alvo de ataques corpo a corpo com armas pesadas ignorando a desvantagem de ataques múltiplos.",
    requisitos: "Armas corpo a corpo pesadas.",
  },

  // --- Mental ---
  {
    nome: "Analisar fraquezas",
    atributo: "Mental",
    custoPA: "1",
    valorCompra: "1",
    efeito: "Vê quanto dano o oponente recebeu em partes do corpo à escolha.",
    requisitos: "Enxergar o componente plenamente.",
  },
  {
    nome: "Auto cura",
    atributo: "Mental",
    custoPA: "4",
    valorCompra: "3",
    efeito: "Realiza um teste de cura de dano superficial em si mesmo.",
    requisitos: "Não estar desabilitado.",
  },
  {
    nome: "Auto tratamento",
    atributo: "Mental",
    custoPA: "5",
    valorCompra: "4",
    efeito: "Realiza um teste de tratamento de dano profundo em si mesmo.",
    requisitos: "Não estar desabilitado.",
  },
  {
    nome: "Criar armadilha",
    atributo: "Mental",
    custoPA: "1",
    valorCompra: "2",
    efeito: "Constrói uma armadilha em terreno adjacente que prende o oponente e causa dano.",
    requisitos: "Estar escondido de qualquer oponente.",
  },
  {
    nome: "Confundir inimigo",
    atributo: "Mental",
    custoPA: "4",
    valorCompra: "3",
    efeito: "Teste mental contra oponentes a até 6 metros para dar desvantagem no próximo contrateste de defesa deles.",
    requisitos: "Os oponentes precisam conseguir te ouvir.",
  },
  {
    nome: "Intimidação generalizada",
    atributo: "Mental",
    custoPA: "4",
    valorCompra: "3",
    efeito: "Teste mental contra oponentes a até 6 metros para atrasar seus turnos em 1 posição.",
    requisitos: "Os oponentes precisam conseguir te ouvir.",
  },
  {
    nome: "Urro de Intimidação",
    atributo: "Mental",
    custoPA: "4",
    valorCompra: "3",
    efeito: "Teste mental contra um oponente a até 3 metros para atrasar o turno dele.",
    requisitos: "Os oponentes precisam conseguir te ouvir.",
  },
  {
    nome: "Recompor",
    atributo: "Mental",
    custoPA: "4",
    valorCompra: "4",
    efeito: "Recupera as próprias aptidões consumidas.",
    requisitos: "Não há.",
  },
  {
    nome: "Consumir",
    atributo: "Mental",
    custoPA: "4",
    valorCompra: "4",
    efeito: "Teste mental para consumir habilidades de um jogador ou desativar habilidades de um NPC.",
    requisitos: "Não há.",
  },

  // --- Social ---
  {
    nome: "Comandar",
    atributo: "Social",
    custoPA: "1",
    valorCompra: "2",
    efeito: "Transfere pontos de ação do seu próximo turno para um aliado.",
    requisitos: "Possuir o PA total a transferir; ver/ouvir e ser visto/ouvido pelo aliado.",
  },
  {
    nome: "Desorientar",
    atributo: "Social",
    custoPA: "4",
    valorCompra: "4",
    efeito: "Teste social que confunde um oponente, fazendo-o perder PA apenas no próximo turno.",
    requisitos: "O oponente precisa conseguir te ouvir.",
  },
  {
    nome: "Cura especializada",
    atributo: "Social",
    custoPA: "4",
    valorCompra: "3",
    efeito: "Realiza um teste de cura de dano superficial em um aliado adjacente.",
    requisitos: "Não estar desabilitado.",
  },
  {
    nome: "Tratamento especializado",
    atributo: "Social",
    custoPA: "5",
    valorCompra: "4",
    efeito: "Realiza um teste de tratamento de dano profundo em um aliado adjacente.",
    requisitos: "Não estar desabilitado.",
  },
  {
    nome: "Grito de alerta",
    atributo: "Social",
    custoPA: "4",
    valorCompra: "3",
    efeito: "Concede vantagem no próximo contrateste de defesa/esquiva para aliados a até 4 metros.",
    requisitos: "Os aliados precisam conseguir te ouvir.",
  },
  {
    nome: "Brado de guerra",
    atributo: "Social",
    custoPA: "2",
    valorCompra: "3",
    efeito: "Concede vantagem no próximo teste de ataque para aliados a até 4 metros.",
    requisitos: "Os aliados precisam conseguir te ouvir.",
  },
  {
    nome: "Revigorar",
    atributo: "Social",
    custoPA: "2",
    valorCompra: "2",
    efeito: "Reativa uma habilidade de um aliado.",
    requisitos: "O aliado precisa conseguir te ouvir.",
  },
  {
    nome: "Revitalizar",
    atributo: "Social",
    custoPA: "7",
    valorCompra: "4",
    efeito: "Teste social que retorna um aliado inconsciente à consciência com tratamento automático.",
    requisitos: "O aliado alvo precisa estar inconsciente.",
  },
  {
    nome: "Animar",
    atributo: "Social",
    custoPA: "2",
    valorCompra: "2",
    efeito: "Teste social para recuperar aptidões consumidas de um aliado.",
    requisitos: "O aliado alvo precisa estar adjacente a você.",
  },
];

// ---------------------------------------------------------------------------
// TRAÇOS (técnicas, maestrias, aspectos)
// ---------------------------------------------------------------------------

export const CAT_TRACOS: CatTraco[] = [
  // --- Técnicas ---
  {
    nome: "Técnica em Agarrar",
    categoria: "Técnica",
    atributo: "Físico",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Agarrar.",
  },
  {
    nome: "Técnica em Empurrar",
    categoria: "Técnica",
    atributo: "Físico",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Empurrar.",
  },
  {
    nome: "Técnica em Arremessar",
    categoria: "Técnica",
    atributo: "Físico",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Arremessar.",
  },
  {
    nome: "Técnica em Saltar",
    categoria: "Técnica",
    atributo: "Ágil",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Saltar.",
  },
  {
    nome: "Técnica em Nadar",
    categoria: "Técnica",
    atributo: "Ágil",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Nadar.",
  },
  {
    nome: "Técnica em Realizar truques",
    categoria: "Técnica",
    atributo: "Ágil ou Social",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Realizar truques.",
  },
  {
    nome: "Técnica em Esconder-se",
    categoria: "Técnica",
    atributo: "Ágil",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Esconder-se.",
  },
  {
    nome: "Técnica em Investigar/Observar",
    categoria: "Técnica",
    atributo: "Mental",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Investigar/Observar.",
  },
  {
    nome: "Técnica em Ponderar",
    categoria: "Técnica",
    atributo: "Mental",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Ponderar.",
  },
  {
    nome: "Técnica em Intimidar",
    categoria: "Técnica",
    atributo: "Social",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Intimidar.",
  },
  {
    nome: "Técnica em Persuadir/Seduzir",
    categoria: "Técnica",
    atributo: "Social",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Persuadir/Seduzir.",
  },
  {
    nome: "Técnica em Performar",
    categoria: "Técnica",
    atributo: "Social",
    valorCompra: "1",
    efeito: "Anula a desvantagem natural dos testes de Performar.",
  },
  {
    nome: "Técnica em Tratar/Curar",
    categoria: "Técnica",
    atributo: "Social ou Mental",
    valorCompra: "3",
    efeito: "Anula a desvantagem natural dos testes de Tratar/Curar.",
  },
  {
    nome: "Técnica em Negociar",
    categoria: "Técnica",
    atributo: "Social ou Mental",
    valorCompra: "3",
    efeito: "Anula a desvantagem natural dos testes de Negociar.",
  },

  // --- Maestrias ---
  {
    nome: "Maestria em armas cortantes (CORT.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Habilita o efeito da propriedade cortante das armas.",
  },
  {
    nome: "Maestria em armas contundentes (CONT.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Habilita o efeito da propriedade contundente das armas.",
  },
  {
    nome: "Maestria em armas perfurantes (PERF.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Habilita o efeito da propriedade perfurante das armas.",
  },
  {
    nome: "Maestria em armas de agarrar (AGAR.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Habilita o efeito da propriedade agarrar das armas.",
  },
  {
    nome: "Maestria em armas versáteis (VERS.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Permite alternar a empunhadura de armas versáteis sem gastar PA.",
  },
  {
    nome: "Maestria em armas de deflexão (DEFL.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Habilita o efeito da propriedade deflexão das armas.",
  },
  {
    nome: "Maestria em projéteis (PROJ.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Habilita o efeito da propriedade projéteis das armas.",
  },
  {
    nome: "Maestria em armaduras leves",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Domínio no uso de armaduras leves.",
  },
  {
    nome: "Maestria em armaduras médias",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Domínio no uso de armaduras médias.",
  },
  {
    nome: "Maestria em armaduras pesadas",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Domínio no uso de armaduras pesadas.",
  },
  {
    nome: "Maestria em ataque desarmado (DESA.)",
    categoria: "Maestria",
    valorCompra: "1",
    efeito: "Permite ataque mirado sem desvantagem, apenas para ataques desarmados.",
  },

  // --- Aspectos ---
  {
    nome: "Empacado",
    categoria: "Aspecto",
    valorCompra: "2",
    efeito: "Reduz qualquer movimentação forçada pela metade (arredondado para baixo).",
    requisitos: "Não ter nenhuma perna desabilitada.",
  },
  {
    nome: "Emboscador",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Dobra o resultado do dano do ataque ao golpear um oponente pelas costas.",
    requisitos: "Estar escondido de todos os oponentes; usar armas leves.",
  },
  {
    nome: "Lépido",
    categoria: "Aspecto",
    valorCompra: "3",
    efeito: "Pode recuar 1 metro imediatamente após acertar um ataque descuidado.",
    requisitos: "Estar utilizando uma arma de longo alcance.",
  },
  {
    nome: "Resistente",
    categoria: "Aspecto",
    valorCompra: "3",
    efeito: "Reduz o dano recebido pela metade.",
    requisitos: "Ter gasto uma guarda levantada para se defender; armadura média ou pesada.",
  },
  {
    nome: "Protetor",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Teste para desviar para si o dano que um aliado adjacente receberia.",
    requisitos: "Estar a 1 metro de um aliado atacado; estar usando escudo.",
  },
  {
    nome: "Blindado",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Defende ataques à distância com +1d10 de vantagem.",
    requisitos: "Estar usando escudo; guarda levantada ao ser atacado à distância.",
  },
  {
    nome: "Vigilante",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Pode desferir um ataque de oportunidade à distância quando um oponente sai do seu alcance ideal.",
    requisitos: "Arma de arremesso equipada; não ter usado o ataque de oportunidade na rodada.",
  },
  {
    nome: "Escorregadio",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Recebe +1d10 de vantagem para esquivar de ataques de oportunidade.",
    requisitos: "Não estar utilizando armadura média ou pesada.",
  },
  {
    nome: "Reativo",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Ataque de oportunidade quando o oponente sai do seu alcance ideal.",
    requisitos: "Estar com guarda levantada; não ter usado o ataque de oportunidade na rodada.",
  },
  {
    nome: "Alerta",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Ataque corpo a corpo descuidado quando um oponente entra no seu alcance ideal.",
    requisitos: "Estar com guarda levantada; não ter usado o ataque de oportunidade na rodada.",
  },
  {
    nome: "Apoiador",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Pode usar aptidões nos testes de um aliado adjacente.",
    requisitos: "Estar adjacente a um aliado; usar aptidões do mesmo atributo da ação.",
  },
  {
    nome: "Corredor",
    categoria: "Aspecto",
    valorCompra: "8",
    efeito: "Dobra o limite de PA que podem ser usados no deslocamento.",
    requisitos: "Não ter pernas desabilitadas.",
  },
  {
    nome: "Maratonista",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Pode dobrar o movimento ao correr em linha reta.",
    requisitos: "Gastar ao menos 5 PA de movimento em linha reta; sem perna desabilitada; sem armas/armaduras pesadas.",
  },
  {
    nome: "Dorminhoco",
    categoria: "Aspecto",
    valorCompra: "7",
    efeito: "Ao descansar, usa 1d8 em vez de 1d6 para curar dano.",
    requisitos: "Descanso longo.",
  },
  {
    nome: "Firme",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Pode usar armas pesadas com apenas uma mão, com -3 de dano.",
    requisitos: "Usar uma arma pesada; não ter nenhuma mão desabilitada.",
  },
  {
    nome: "Firme aprimorado",
    categoria: "Aspecto",
    valorCompra: "4",
    efeito: "Remove a redução de dano do Firme: usa armas pesadas com uma mão sem redução de dano.",
    requisitos: "Possuir o traço Firme; não ter nenhuma mão desabilitada.",
  },
  {
    nome: "Saltador",
    categoria: "Aspecto",
    valorCompra: "3",
    efeito: "Eleva o limite de salto de 5 metros para 10 metros.",
    requisitos: "Possuir a Técnica em Saltar; sem perna desabilitada.",
  },
  {
    nome: "Burro de carga",
    categoria: "Aspecto",
    valorCompra: "6",
    efeito: "Não gasta PA extra para deslocar um aliado que esteja agarrado.",
    requisitos: "O aliado só pode ser carregado de forma voluntária.",
  },
];

// ---------------------------------------------------------------------------
// PROPRIEDADES DAS ARMAS (glossário + maestria correspondente)
// ---------------------------------------------------------------------------

export type PropInfo = {
  nome: string;
  efeito: string;
  /** traço de maestria que ativa a propriedade (undefined = não exige maestria). */
  maestria?: string;
};

export const PROP_INFO: Record<PropKey, PropInfo> = {
  CORT: {
    nome: "Cortante",
    efeito:
      "Ataque de oportunidade quando o alvo se move para te CONTORNAR (rodeia dentro do seu alcance ideal). Consome a reação. (Sair do alcance já provoca AoO de qualquer arma.)",
    maestria: "Maestria em armas cortantes",
  },
  CONT: {
    nome: "Contundente",
    efeito:
      "Ao acertar, reduz PA do alvo sem teste até o próximo turno dele (leve −1, média −2, pesada −3).",
    maestria: "Maestria em armas contundentes",
  },
  PERF: {
    nome: "Perfurante",
    efeito:
      "Expande o engajamento: permite um ataque de oportunidade quando o alvo ENTRA no seu alcance ideal (consome a reação).",
    maestria: "Maestria em armas perfurantes",
  },
  AGAR: {
    nome: "Agarrar",
    efeito: "Concede vantagem para a ação Agarrar.",
    maestria: "Maestria em armas de agarrar",
  },
  DEFL: {
    nome: "Deflexão",
    efeito: "Ignora um dado de desvantagem em contratestes de defesa.",
    maestria: "Maestria em armas de deflexão",
  },
  PROJ: {
    nome: "Projéteis",
    efeito:
      "Ignora barreiras no caminho do alvo (se não estiverem acima dele); ao acertar, recarregar não custa PA.",
    maestria: "Maestria em projéteis",
  },
  ARRE: {
    nome: "Arremesso",
    efeito:
      "Ignora um dado de desvantagem ao arremessar. Sem a propriedade, arremessar é ataque com desvantagem (fora do alcance ideal, +2d10).",
  },
};
